services:
  spark-master:
    image: bitnami/spark:3.5.5
    container_name: spark-master
    ports:
      - "8080:8080"  # Web UI
      - "7077:7077"  # Spark Master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - spark-data:/opt/bitnami/spark/data
    networks:
      - postgres-network

  spark-worker-1:
    image: bitnami/spark:3.5.5
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Web UI for worker 1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - spark-data:/opt/bitnami/spark/data
    networks:
      - postgres-network

networks:
  postgres-network:

volumes:
  spark-data:
